/** Plain-language definitions shown as hover tooltips. */
export const GLOSSARY: Record<string, string> = {
  lot: 'A single parcel of land, as drawn on the county tax map.',
  'zoning district': 'The city-assigned category (like R1D-L or RM-M) that says what can be built on a lot and how big it must be.',
  variance: 'Permission from the Zoning Board of Adjustment to break a zoning rule (for example, building on a lot that is too small).',
  'use variance': 'A variance to build something the district does not allow at all (for example, housing in a highway-commercial district).',
  ADU: 'Accessory dwelling unit: a small extra home on the same lot as a main house (a backyard cottage, garage apartment, or basement unit).',
  'by right': 'Allowed automatically if you meet the rules, with no special hearing.',
  'special exception': 'Allowed only after a hearing and approval by the Zoning Board of Adjustment.',
  'administrator exception': 'Allowed only if the Zoning Administrator reviews and approves it.',
  'geotechnical review': 'An engineer checks whether the ground (steep slope, landslide-prone soil, old mine voids) can safely support a building. Required by Pittsburgh Zoning Code Ch. 915.',
  undermined: 'Old coal mines run beneath the land and the ground may settle or collapse.',
  'flood zone': 'Land FEMA maps as having a 1% or greater yearly chance of flooding (Special Flood Hazard Area).',
  'inclusionary zoning': 'A rule that requires some new homes in certain neighborhoods to be affordable to lower-income households.',
  'historic district': 'An area where exterior changes and new buildings need design review by the Historic Review Commission.',
  'PWSA': 'Pittsburgh Water and Sewer Authority. A developer requests an availability letter to confirm water and sewer service.',
  PHFA: 'Pennsylvania Housing Finance Agency, which awards housing tax credits and other funding.',
  'gap financing': 'Extra funding needed when the cost to build is more than the finished homes are worth.',
  HACP: 'Housing Authority of the City of Pittsburgh.',
  URA: 'Urban Redevelopment Authority of Pittsburgh.',
  GIS: 'Geographic information system: digital map data.',
  'transit buffer': 'The area within about 1,500 feet of a major transit stop or line.',
  'lot minimum': 'The smallest lot size the zoning district allows for building a home.',
};
